kind: ReplicationController
apiVersion: v1
metadata:
  name: kube-dns
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    version: v1.0.0
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    spec:
      dnsPolicy: "Default"
      containers:
      - name: etcd
        image: gcr.io/google_containers/etcd:2.0.9
        command:
        - /usr/local/bin/etcd
        - -listen-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -advertise-client-urls
        - http://127.0.0.1:2379,http://127.0.0.1:4001
        - -initial-cluster-token
        - skydns-etcd
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.10
        args:
        # command = "/kube2sky"
        - -domain=cluster.local
        - -kube_master_url=http://<master ip>:8080
        - -v=4
      - name: skydns
        image: gcr.io/google_containers/skydns:2015-03-11-001
        args:
        - -machines=http://localhost:4001
        - -addr=0.0.0.0:53
        - -domain=cluster.local
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - nslookup kubernetes.default.svc.cluster.local localhost >/dev/null
          initialDelaySeconds: 30
          timeoutSeconds: 5
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"